### ISSUE TITLE
Problem with width on the issue view

### ISSUE THREAD

**Issue by dgutkowsky** [tsi/redmine-theme-flat#11]
When I set a window too wide, the properties of the issue got separated by a lot of free space. When I decrease the window width it displays the issue properties ok.

![image](https://cloud.githubusercontent.com/assets/4732829/6070929/1b123172-ad91-11e4-958b-eeb327770595.png)

![image](https://cloud.githubusercontent.com/assets/4732829/6070937/2dc0bd5c-ad91-11e4-935f-e7c738ca9c9b.png)

**Comment by tsi** [comment]
I have no way of telling what is causing this, just tested with a window spread across 2 screens (1980*2) with no issue, can you share any more details?
