### ISSUE TITLE
Changing things in application.sass does not reflect on browser

### ISSUE THREAD

**Issue by thuantran** [tsi/redmine-theme-flat#12]
Sorry but I'm noob with ruby and web programming language. I have tried to change the color and an url in application.sass like so:

``` css
// Open Sans
@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800);

$gray-dark: #202020;
$gray-text: #484848;
//$hotpink: #d92e47;
$hotpink: #33b5e5;
```

but it doesn't reflect on my browser. What should I do?

Thanks and best regards,
Thuan

**Comment by tsi** [comment]
You must re-compile your Sass.
There are many ways to do that, see http://sass-lang.com/install

**Comment by thuantran** [comment]
Yep, I've done it. I thought I just need to edit that sass file. Learnt something new.

Thanks.
