### ISSUE TITLE
No style for `<code>` element

### ISSUE THREAD

**Issue by ArmorDarks** [tsi/redmine-theme-flat#14]
There is no styles for `<code>` element, which makes it hard sometimes to distinguish `<code>` from common text.

Here are styles, which will style it similarly to the block code elements:

``` scss
padding-top: 0.2em;
padding-right: 0.4em;
padding-bottom: 0.2em;
padding-left: 0.4em;

font-size: 85%;

background-color: #fafafa;
border: 1px solid #e2e2e2;
```

Demo:
![l9dsmyq](https://cloud.githubusercontent.com/assets/4460311/9891937/edd28096-5c12-11e5-8a6e-42ba466c2d0b.png)

Against original: 
![nfdin8y](https://cloud.githubusercontent.com/assets/4460311/9891947/066cfe60-5c13-11e5-8d36-1b64225c3345.png)

Paddings and font size inherited from Github's styling for `<code>` element.

I'd make PR, but so far there is no section for `.wiki code` styles. Where should I put those?

**Comment by tsi** [comment]
https://github.com/tsi/redmine-theme-flat/commit/ecd7f6b4fd564a9b72ad7bff68009ba3dfb3d62f
Thanks!
