### ISSUE TITLE
add observer not displayed 

### ISSUE THREAD

**Issue by Reeslo** [tsi/redmine-theme-flat#9]
I don't know if its not implemented or yes, but when you edit or create an issue,
you can't assign observer/whatcher to the current issue.

thanks

**Comment by ArmorDarks** [comment]
Checked in our Redmine with that theme installed — no issues:
![2015-09-16_01-15-00](https://cloud.githubusercontent.com/assets/4460311/9891639/73f3509a-5c10-11e5-94fa-290c4f373c67.png)

**Comment by tsi** [comment]
Thanks
